# config.properties
# Database connection settings

# --- Auth DB Connection ---
auth.db.url=jdbc:mysql://localhost:3306/auth_db
auth.db.user=root
auth.db.pass=1234

# --- ERP DB Connection ---
erp.db.url=jdbc:mysql://localhost:3306/erp_db
erp.db.user=root
erp.db.pass=1234